# Generated by Django 5.2.15 on 2026-08-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testseries',
            name='test_type',
            field=models.CharField(choices=[('COMPANY', 'Company Specific PYQs'), ('TOPIC', 'Topic Wise Practice'), ('OTHER', 'Pattern-Crafted Mock Tests')], default='COMPANY', max_length=20),
        ),
    ]
