# Generated by Django 5.2.15 on 2026-08-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_testseries_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='integrity_flag',
            field=models.BooleanField(default=False, help_text='True if attempt was auto-submitted or flagged for excessive tab switching'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='submission_reason',
            field=models.CharField(default='Normal Submission', help_text='Reason for test completion', max_length=255),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='tab_switches_count',
            field=models.IntegerField(default=0, help_text='Number of tab switches or window blur events detected during test'),
        ),
    ]
