# Generated by Django 5.2.15 on 2026-08-25 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_testattempt_integrity_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='is_mega_event_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MegaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('banner_tag', models.CharField(default='ALL-INDIA MEGA RECRUITMENT DRIVE', max_length=150)),
                ('company_tag', models.CharField(default='TCS NQT 2026', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_leaderboard_revealed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mega_events', to='portal.testseries')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='testattempt',
            name='mega_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='portal.megaevent'),
        ),
        migrations.CreateModel(
            name='BookmarkedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='portal.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
