# Generated by Django 5.2.15 on 2026-09-05 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_testattempt_is_mega_event_attempt_megaevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(db_index=True, max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('source_code', models.TextField()),
                ('status', models.CharField(default='ACCEPTED', max_length=50)),
                ('passed_test_cases', models.IntegerField(default=0)),
                ('total_test_cases', models.IntegerField(default=0)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('test_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.testseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTestProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('VISITED', 'Visited'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('mode', models.CharField(default='exam', max_length=20)),
                ('last_visited_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='portal.testseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_visited_at'],
                'unique_together': {('user', 'test')},
            },
        ),
    ]
