# Generated by Django 5.2.15 on 2026-09-05 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_codingsubmission_usertestprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='testseries',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='testseries',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('STAFF_ADMIN', 'Staff Admin'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='testseries',
            name='test_type',
            field=models.CharField(choices=[('COMPANY', 'Company Specific PYQs'), ('TOPIC', 'Topic Wise Practice'), ('FOUNDATION', 'Foundation & Sectional'), ('CODING', 'Coding & Technical'), ('OTHER', 'Pattern-Crafted Mock Tests')], default='COMPANY', max_length=20),
        ),
    ]
