services:
  - type: web
    name: firstround-portal
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python populate_db.py"
    startCommand: "gunicorn firstround_core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: firstround-db
          property: connectionString

databases:
  - name: firstround-db
    plan: free
